### Run test locally

@runHost = 172.23.144.141
POST http://{{runHost}}:1234/test/run
Content-Type: application/json

{
  "serviceName": "test-local",
  "token": "test-local",
  "ratePerSecond": 1000,
  "testCount": 200000,
  "processingTimeMillis": 50000,
  "onPremises": false
}

### Stop running test to save time and resources
# @timeout 120
POST http://{{runHost}}:1234/test/stop/test-local