### Run test locally

@runHost = localhost
POST http://{{runHost}}:1234/test/run
Content-Type: application/json

{
  "serviceName": "test-local",
  "token": "test-local",
  "ratePerSecond": 3,
  "testCount": 1050,
  "processingTimeMillis": 26000,
  "runits": 90,
  "onPremises": false
}

### Stop running test to save time and resources
# @timeout 120
POST http://{{runHost}}:1234/test/stop/{{serviceName}}